// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 服务器
type ServerOrder int32

const (
	ServerOrder_SERERORDER_LOGIN  ServerOrder = 0
	ServerOrder_SERERORDER_SIGNUP ServerOrder = 1
)

var ServerOrder_name = map[int32]string{
	0: "SERERORDER_LOGIN",
	1: "SERERORDER_SIGNUP",
}

var ServerOrder_value = map[string]int32{
	"SERERORDER_LOGIN":  0,
	"SERERORDER_SIGNUP": 1,
}

func (x ServerOrder) String() string {
	return proto.EnumName(ServerOrder_name, int32(x))
}

func (ServerOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

// 客户端
type ClientOrder int32

const (
	ClientOrder_CLIENORDER_LOGIN  ClientOrder = 0
	ClientOrder_CLIENORDER_SIGNUP ClientOrder = 1
)

var ClientOrder_name = map[int32]string{
	0: "CLIENORDER_LOGIN",
	1: "CLIENORDER_SIGNUP",
}

var ClientOrder_value = map[string]int32{
	"CLIENORDER_LOGIN":  0,
	"CLIENORDER_SIGNUP": 1,
}

func (x ClientOrder) String() string {
	return proto.EnumName(ClientOrder_name, int32(x))
}

func (ClientOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

type Login struct {
	Istrue               bool     `protobuf:"varint,1,opt,name=istrue,proto3" json:"istrue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetIstrue() bool {
	if m != nil {
		return m.Istrue
	}
	return false
}

type SIGNUP struct {
	Istrue               bool     `protobuf:"varint,1,opt,name=istrue,proto3" json:"istrue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIGNUP) Reset()         { *m = SIGNUP{} }
func (m *SIGNUP) String() string { return proto.CompactTextString(m) }
func (*SIGNUP) ProtoMessage()    {}
func (*SIGNUP) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SIGNUP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIGNUP.Unmarshal(m, b)
}
func (m *SIGNUP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIGNUP.Marshal(b, m, deterministic)
}
func (m *SIGNUP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIGNUP.Merge(m, src)
}
func (m *SIGNUP) XXX_Size() int {
	return xxx_messageInfo_SIGNUP.Size(m)
}
func (m *SIGNUP) XXX_DiscardUnknown() {
	xxx_messageInfo_SIGNUP.DiscardUnknown(m)
}

var xxx_messageInfo_SIGNUP proto.InternalMessageInfo

func (m *SIGNUP) GetIstrue() bool {
	if m != nil {
		return m.Istrue
	}
	return false
}

//服务器协议
type ServerMessage struct {
	Order                ServerOrder `protobuf:"varint,1,opt,name=order,proto3,enum=pb.ServerOrder" json:"order,omitempty"`
	Login                *Login      `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Signup               *SIGNUP     `protobuf:"bytes,3,opt,name=signup,proto3" json:"signup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetOrder() ServerOrder {
	if m != nil {
		return m.Order
	}
	return ServerOrder_SERERORDER_LOGIN
}

func (m *ServerMessage) GetLogin() *Login {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *ServerMessage) GetSignup() *SIGNUP {
	if m != nil {
		return m.Signup
	}
	return nil
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//客户端协议
type ClientMessage struct {
	Order                ClientOrder `protobuf:"varint,1,opt,name=order,proto3,enum=pb.ClientOrder" json:"order,omitempty"`
	User                 *User       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func (m *ClientMessage) GetOrder() ClientOrder {
	if m != nil {
		return m.Order
	}
	return ClientOrder_CLIENORDER_LOGIN
}

func (m *ClientMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.ServerOrder", ServerOrder_name, ServerOrder_value)
	proto.RegisterEnum("pb.ClientOrder", ClientOrder_name, ClientOrder_value)
	proto.RegisterType((*Login)(nil), "pb.Login")
	proto.RegisterType((*SIGNUP)(nil), "pb.SIGNUP")
	proto.RegisterType((*ServerMessage)(nil), "pb.ServerMessage")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*ClientMessage)(nil), "pb.ClientMessage")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4b, 0x84, 0x40,
	0x14, 0x87, 0x73, 0x5b, 0x45, 0xdf, 0xb2, 0x65, 0x43, 0x85, 0x44, 0xb0, 0x22, 0x04, 0x4b, 0x07,
	0x0f, 0xdb, 0xad, 0x43, 0x97, 0x4d, 0x16, 0xc1, 0x34, 0x9e, 0xed, 0x39, 0x94, 0x1d, 0x44, 0xd8,
	0x74, 0x98, 0xd1, 0x3a, 0xf4, 0xcf, 0xc7, 0xcc, 0xd8, 0x62, 0x44, 0x1d, 0xdf, 0xef, 0x7d, 0x6f,
	0xde, 0xf7, 0x18, 0x80, 0x5e, 0x50, 0x1e, 0x32, 0xde, 0x76, 0x2d, 0x99, 0xb0, 0x32, 0x58, 0x80,
	0x99, 0xb4, 0x55, 0xdd, 0x90, 0x4b, 0xb0, 0x6a, 0xd1, 0xf1, 0x9e, 0x7a, 0x86, 0x6f, 0x2c, 0x6d,
	0x1c, 0xaa, 0xc0, 0x07, 0x2b, 0x8f, 0x37, 0xe9, 0xf6, 0xf9, 0x4f, 0xe2, 0x13, 0xe6, 0x39, 0xe5,
	0xef, 0x94, 0x3f, 0x51, 0x21, 0x8a, 0x8a, 0x92, 0x1b, 0x30, 0x5b, 0xbe, 0xa3, 0x5c, 0x71, 0x27,
	0xab, 0xd3, 0x90, 0x95, 0xa1, 0x26, 0x32, 0x19, 0xa3, 0xee, 0x92, 0x05, 0x98, 0x7b, 0xb9, 0xda,
	0x9b, 0xf8, 0xc6, 0x72, 0xb6, 0x72, 0x24, 0xa6, 0x5c, 0x50, 0xe7, 0x24, 0x00, 0x4b, 0xd4, 0x55,
	0xd3, 0x33, 0xef, 0x58, 0x11, 0xa0, 0x1e, 0x52, 0x32, 0x38, 0x74, 0x82, 0x07, 0x98, 0x6e, 0x05,
	0xe5, 0xe4, 0x0a, 0x6c, 0x79, 0x59, 0x53, 0xbc, 0x69, 0x3d, 0x07, 0x0f, 0xb5, 0xec, 0xb1, 0x42,
	0x88, 0x8f, 0x96, 0xef, 0xd4, 0x2e, 0x07, 0x0f, 0x75, 0xf0, 0x02, 0xf3, 0xf5, 0xbe, 0xa6, 0x4d,
	0xf7, 0x9f, 0xbc, 0x26, 0x7e, 0xc8, 0x5f, 0xc3, 0x54, 0xbe, 0x3f, 0xb8, 0xdb, 0x92, 0x92, 0x1e,
	0xa8, 0xd2, 0xdb, 0x7b, 0x98, 0x8d, 0x0e, 0x26, 0xe7, 0xe0, 0xe6, 0x11, 0x46, 0x98, 0xe1, 0x63,
	0x84, 0xaf, 0x49, 0xb6, 0x89, 0x53, 0xf7, 0x88, 0x5c, 0xc0, 0xd9, 0x28, 0xd5, 0x77, 0xb9, 0x86,
	0x9c, 0x1d, 0xed, 0x93, 0xb3, 0xeb, 0x24, 0x8e, 0xd2, 0x5f, 0xb3, 0xa3, 0xf4, 0x7b, 0xb6, 0xb4,
	0xd4, 0xc7, 0xde, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xe6, 0xa2, 0x5e, 0xe6, 0x01, 0x00,
	0x00,
}
