// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 服务器
type ServerOrder int32

const (
	ServerOrder_SERERORDER_LOGIN         ServerOrder = 0
	ServerOrder_SERERORDER_SIGNUP        ServerOrder = 1
	ServerOrder_SERERORDER_SEND_WAITTIME ServerOrder = 2
	ServerOrder_SERERORDER_SEND_QUESTION ServerOrder = 3
)

var ServerOrder_name = map[int32]string{
	0: "SERERORDER_LOGIN",
	1: "SERERORDER_SIGNUP",
	2: "SERERORDER_SEND_WAITTIME",
	3: "SERERORDER_SEND_QUESTION",
}

var ServerOrder_value = map[string]int32{
	"SERERORDER_LOGIN":         0,
	"SERERORDER_SIGNUP":        1,
	"SERERORDER_SEND_WAITTIME": 2,
	"SERERORDER_SEND_QUESTION": 3,
}

func (x ServerOrder) String() string {
	return proto.EnumName(ServerOrder_name, int32(x))
}

func (ServerOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

// 客户端
type ClientOrder int32

const (
	ClientOrder_CLIENORDER_LOGIN        ClientOrder = 0
	ClientOrder_CLIENORDER_SIGNUP       ClientOrder = 1
	ClientOrder_CLIENORDER_GET_WAITTIME ClientOrder = 2
	ClientOrder_CLIENORDER_GET_QUESTION ClientOrder = 3
)

var ClientOrder_name = map[int32]string{
	0: "CLIENORDER_LOGIN",
	1: "CLIENORDER_SIGNUP",
	2: "CLIENORDER_GET_WAITTIME",
	3: "CLIENORDER_GET_QUESTION",
}

var ClientOrder_value = map[string]int32{
	"CLIENORDER_LOGIN":        0,
	"CLIENORDER_SIGNUP":       1,
	"CLIENORDER_GET_WAITTIME": 2,
	"CLIENORDER_GET_QUESTION": 3,
}

func (x ClientOrder) String() string {
	return proto.EnumName(ClientOrder_name, int32(x))
}

func (ClientOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

type Time struct {
	Hour                 int32    `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute               int32    `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	Second               int32    `protobuf:"varint,3,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *Time) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *Time) GetSecond() int32 {
	if m != nil {
		return m.Second
	}
	return 0
}

type Question struct {
	QuestionId           int32    `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Question             string   `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	A                    string   `protobuf:"bytes,4,opt,name=A,proto3" json:"A,omitempty"`
	B                    string   `protobuf:"bytes,5,opt,name=B,proto3" json:"B,omitempty"`
	C                    string   `protobuf:"bytes,6,opt,name=C,proto3" json:"C,omitempty"`
	D                    string   `protobuf:"bytes,7,opt,name=D,proto3" json:"D,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetQuestionId() int32 {
	if m != nil {
		return m.QuestionId
	}
	return 0
}

func (m *Question) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *Question) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *Question) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *Question) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *Question) GetC() string {
	if m != nil {
		return m.C
	}
	return ""
}

func (m *Question) GetD() string {
	if m != nil {
		return m.D
	}
	return ""
}

type Login struct {
	Istrue               bool     `protobuf:"varint,1,opt,name=istrue,proto3" json:"istrue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetIstrue() bool {
	if m != nil {
		return m.Istrue
	}
	return false
}

type SIGNUP struct {
	Istrue               bool     `protobuf:"varint,1,opt,name=istrue,proto3" json:"istrue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIGNUP) Reset()         { *m = SIGNUP{} }
func (m *SIGNUP) String() string { return proto.CompactTextString(m) }
func (*SIGNUP) ProtoMessage()    {}
func (*SIGNUP) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SIGNUP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIGNUP.Unmarshal(m, b)
}
func (m *SIGNUP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIGNUP.Marshal(b, m, deterministic)
}
func (m *SIGNUP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIGNUP.Merge(m, src)
}
func (m *SIGNUP) XXX_Size() int {
	return xxx_messageInfo_SIGNUP.Size(m)
}
func (m *SIGNUP) XXX_DiscardUnknown() {
	xxx_messageInfo_SIGNUP.DiscardUnknown(m)
}

var xxx_messageInfo_SIGNUP proto.InternalMessageInfo

func (m *SIGNUP) GetIstrue() bool {
	if m != nil {
		return m.Istrue
	}
	return false
}

type WAITTIME struct {
	Start                bool     `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Time                 *Time    `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WAITTIME) Reset()         { *m = WAITTIME{} }
func (m *WAITTIME) String() string { return proto.CompactTextString(m) }
func (*WAITTIME) ProtoMessage()    {}
func (*WAITTIME) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *WAITTIME) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WAITTIME.Unmarshal(m, b)
}
func (m *WAITTIME) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WAITTIME.Marshal(b, m, deterministic)
}
func (m *WAITTIME) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WAITTIME.Merge(m, src)
}
func (m *WAITTIME) XXX_Size() int {
	return xxx_messageInfo_WAITTIME.Size(m)
}
func (m *WAITTIME) XXX_DiscardUnknown() {
	xxx_messageInfo_WAITTIME.DiscardUnknown(m)
}

var xxx_messageInfo_WAITTIME proto.InternalMessageInfo

func (m *WAITTIME) GetStart() bool {
	if m != nil {
		return m.Start
	}
	return false
}

func (m *WAITTIME) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

type QUESTION struct {
	Num                  int32       `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Ques                 []*Question `protobuf:"bytes,2,rep,name=ques,proto3" json:"ques,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QUESTION) Reset()         { *m = QUESTION{} }
func (m *QUESTION) String() string { return proto.CompactTextString(m) }
func (*QUESTION) ProtoMessage()    {}
func (*QUESTION) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *QUESTION) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QUESTION.Unmarshal(m, b)
}
func (m *QUESTION) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QUESTION.Marshal(b, m, deterministic)
}
func (m *QUESTION) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QUESTION.Merge(m, src)
}
func (m *QUESTION) XXX_Size() int {
	return xxx_messageInfo_QUESTION.Size(m)
}
func (m *QUESTION) XXX_DiscardUnknown() {
	xxx_messageInfo_QUESTION.DiscardUnknown(m)
}

var xxx_messageInfo_QUESTION proto.InternalMessageInfo

func (m *QUESTION) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *QUESTION) GetQues() []*Question {
	if m != nil {
		return m.Ques
	}
	return nil
}

//服务器协议
type ServerMessage struct {
	Order                ServerOrder `protobuf:"varint,1,opt,name=order,proto3,enum=pb.ServerOrder" json:"order,omitempty"`
	Login                *Login      `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Signup               *SIGNUP     `protobuf:"bytes,3,opt,name=signup,proto3" json:"signup,omitempty"`
	Wait                 *WAITTIME   `protobuf:"bytes,4,opt,name=wait,proto3" json:"wait,omitempty"`
	Quess                *QUESTION   `protobuf:"bytes,5,opt,name=quess,proto3" json:"quess,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetOrder() ServerOrder {
	if m != nil {
		return m.Order
	}
	return ServerOrder_SERERORDER_LOGIN
}

func (m *ServerMessage) GetLogin() *Login {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *ServerMessage) GetSignup() *SIGNUP {
	if m != nil {
		return m.Signup
	}
	return nil
}

func (m *ServerMessage) GetWait() *WAITTIME {
	if m != nil {
		return m.Wait
	}
	return nil
}

func (m *ServerMessage) GetQuess() *QUESTION {
	if m != nil {
		return m.Quess
	}
	return nil
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//客户端协议
type ClientMessage struct {
	Order                ClientOrder `protobuf:"varint,1,opt,name=order,proto3,enum=pb.ClientOrder" json:"order,omitempty"`
	User                 *User       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func (m *ClientMessage) GetOrder() ClientOrder {
	if m != nil {
		return m.Order
	}
	return ClientOrder_CLIENORDER_LOGIN
}

func (m *ClientMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.ServerOrder", ServerOrder_name, ServerOrder_value)
	proto.RegisterEnum("pb.ClientOrder", ClientOrder_name, ClientOrder_value)
	proto.RegisterType((*Time)(nil), "pb.Time")
	proto.RegisterType((*Question)(nil), "pb.Question")
	proto.RegisterType((*Login)(nil), "pb.Login")
	proto.RegisterType((*SIGNUP)(nil), "pb.SIGNUP")
	proto.RegisterType((*WAITTIME)(nil), "pb.WAITTIME")
	proto.RegisterType((*QUESTION)(nil), "pb.QUESTION")
	proto.RegisterType((*ServerMessage)(nil), "pb.ServerMessage")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*ClientMessage)(nil), "pb.ClientMessage")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x49, 0x9b, 0x94, 0xf6, 0xb2, 0x41, 0xb0, 0x06, 0x44, 0x30, 0xa9, 0x55, 0x24, 0xa4,
	0x69, 0x0f, 0x7d, 0x28, 0xef, 0x93, 0xba, 0x36, 0xaa, 0x82, 0xba, 0x96, 0xb9, 0xa9, 0x78, 0xac,
	0x52, 0x6a, 0x15, 0x4b, 0x6b, 0x12, 0x6c, 0x67, 0xfd, 0x28, 0x7c, 0x1e, 0xbe, 0x19, 0x3a, 0xdb,
	0x29, 0x41, 0x03, 0xde, 0xfc, 0xff, 0xdf, 0xf9, 0xee, 0xfc, 0xbb, 0x04, 0xa0, 0x92, 0x4c, 0x0c,
	0x4b, 0x51, 0xa8, 0x82, 0xb4, 0xca, 0x6d, 0xf4, 0x09, 0xdc, 0x94, 0x1f, 0x18, 0x21, 0xe0, 0x7e,
	0x2b, 0x2a, 0x11, 0x3a, 0x03, 0xe7, 0xca, 0xa3, 0xfa, 0x4c, 0xde, 0x40, 0xe7, 0xc0, 0xf3, 0x4a,
	0xb1, 0xb0, 0xa5, 0x5d, 0xab, 0xd0, 0x97, 0xec, 0x6b, 0x91, 0xef, 0xc2, 0xb6, 0xf1, 0x8d, 0x8a,
	0x7e, 0x38, 0xd0, 0xbd, 0xaf, 0x98, 0x54, 0xbc, 0xc8, 0x49, 0x1f, 0xfc, 0xef, 0xf6, 0xbc, 0xe1,
	0x3b, 0x5b, 0x17, 0x6a, 0x2b, 0xd9, 0x61, 0x95, 0x2c, 0x97, 0x47, 0x26, 0x74, 0xf5, 0x1e, 0xb5,
	0x8a, 0xbc, 0x83, 0x6e, 0x9d, 0xa5, 0xeb, 0xf7, 0xe8, 0x49, 0x93, 0x33, 0x70, 0xc6, 0xa1, 0xab,
	0x4d, 0x67, 0x8c, 0xea, 0x36, 0xf4, 0x8c, 0xba, 0x45, 0x35, 0x09, 0x3b, 0x46, 0x4d, 0x50, 0x4d,
	0xc3, 0xe7, 0x46, 0x4d, 0xa3, 0x3e, 0x78, 0xf3, 0x62, 0xcf, 0x73, 0x6c, 0xca, 0xa5, 0x12, 0x15,
	0xd3, 0x03, 0x75, 0xa9, 0x55, 0xd1, 0x00, 0x3a, 0xab, 0x64, 0xb6, 0x58, 0x7f, 0xfe, 0x67, 0xc6,
	0x0d, 0x74, 0xbf, 0x8c, 0x93, 0x34, 0x4d, 0xee, 0x62, 0x72, 0x01, 0x9e, 0x54, 0x99, 0x50, 0x36,
	0xc5, 0x08, 0x72, 0x09, 0xae, 0xe2, 0x07, 0x03, 0xcb, 0x1f, 0x75, 0x87, 0xe5, 0x76, 0x88, 0x68,
	0xa9, 0x76, 0xf1, 0xfe, 0xfd, 0x3a, 0x5e, 0xa5, 0xc9, 0x72, 0x41, 0x02, 0x68, 0xe7, 0xd5, 0xc1,
	0x32, 0xc1, 0x23, 0x19, 0x80, 0x8b, 0x8f, 0x0c, 0x5b, 0x83, 0xf6, 0x95, 0x3f, 0x3a, 0xc3, 0xbb,
	0x35, 0x49, 0xaa, 0x23, 0xd1, 0x4f, 0x07, 0xce, 0x57, 0x4c, 0x3c, 0x32, 0x71, 0xc7, 0xa4, 0xcc,
	0xf6, 0x8c, 0x7c, 0x00, 0xaf, 0x10, 0x3b, 0x66, 0x76, 0xf6, 0x62, 0xf4, 0x12, 0x2f, 0x99, 0x8c,
	0x25, 0xda, 0xd4, 0x44, 0x49, 0x1f, 0xbc, 0x07, 0x7c, 0xbb, 0x9d, 0xab, 0x87, 0x69, 0x1a, 0x06,
	0x35, 0x3e, 0x89, 0xa0, 0x23, 0xf9, 0x3e, 0xaf, 0x4a, 0x8d, 0xdb, 0x1f, 0x81, 0x2e, 0xa4, 0x69,
	0x50, 0x1b, 0xc1, 0xf9, 0x8e, 0x19, 0x57, 0x9a, 0xbd, 0x9d, 0xaf, 0xa6, 0x41, 0x75, 0x84, 0x44,
	0xe0, 0xe1, 0x9c, 0x52, 0x2f, 0xa4, 0x7e, 0x82, 0x7d, 0x30, 0x35, 0xa1, 0xe8, 0x06, 0xdc, 0xb5,
	0x34, 0x2b, 0xc6, 0xcf, 0x30, 0xcf, 0x0e, 0x86, 0x72, 0x8f, 0x9e, 0x34, 0xc6, 0xca, 0x4c, 0xca,
	0x63, 0x21, 0x76, 0xf6, 0xc3, 0x38, 0xe9, 0x28, 0x85, 0xf3, 0xc9, 0x03, 0x67, 0xb9, 0xfa, 0x1f,
	0x02, 0x93, 0xf1, 0x07, 0x82, 0x4b, 0x70, 0xb1, 0x7e, 0x73, 0x33, 0x38, 0x07, 0xd5, 0xee, 0xf5,
	0x23, 0xf8, 0x0d, 0x6c, 0xe4, 0x02, 0x82, 0x55, 0x4c, 0x63, 0xba, 0xa4, 0xd3, 0x98, 0x6e, 0xe6,
	0xcb, 0x59, 0xb2, 0x08, 0x9e, 0x91, 0xd7, 0xf0, 0xaa, 0xe1, 0x1a, 0x3a, 0x81, 0x43, 0x2e, 0x21,
	0x6c, 0xda, 0xf1, 0x62, 0xba, 0xa9, 0xb9, 0x04, 0xad, 0xbf, 0x45, 0x6b, 0x24, 0x41, 0xfb, 0x5a,
	0x81, 0xdf, 0x98, 0x15, 0xfb, 0x4e, 0xe6, 0x49, 0xbc, 0x78, 0xd2, 0xb7, 0xe1, 0x9e, 0xfa, 0xbe,
	0x87, 0xb7, 0x0d, 0x7b, 0x16, 0xa7, 0xcd, 0xb6, 0x4f, 0x83, 0xbf, 0xbb, 0x6e, 0x3b, 0xfa, 0xdf,
	0xff, 0xf8, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x33, 0xb5, 0xcc, 0x90, 0x09, 0x04, 0x00, 0x00,
}
